import {
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  faFileAlt,
  faInfoCircle,
  faHistory, // ✅ AJOUTÉ : Pour l'historique
  faChevronLeft, // ✅ AJOUTÉ : Pour la pagination
  faChevronRight, // ✅ AJOUTÉ : Pour la pagination
  faFilter, // ✅ AJOUTÉ : Pour l'icône de filtre
  faBuilding, // ✅ AJOUTÉ
  faBriefcase, // ✅ AJOUTÉ
  faArrowRight,
  // jhipster-needle-add-icon-import
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  faFileAlt,
  faInfoCircle,
  faHistory, // ✅ AJOUTÉ
  faChevronLeft, // ✅ AJOUTÉ
  faChevronRight, // ✅ AJOUTÉ
  faFilter, // ✅ AJOUTÉ
  faBuilding, // ✅ AJOUTÉ
  faBriefcase, // ✅ AJOUTÉ
  faArrowRight,
  // jhipster-needle-add-icon-import
];
