# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: paieZoneRH
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MmI3YzEwM2MzNzZjZmIzMmJkNTU5MDlkNjk5MGI5ZDZjZmIxNmQ4ODc3OWViZDA0MDI2ODhiMWQzMzM0NDkzOGRmMDlmNTllN2IyMjVlY2ZkNTkzZDdlNWM2N2U5MGRhNmIwNWMwMDY4NWZjODgzZDUzMjViYTBlMjBiZDM5NDM=
