export enum OfficialDocType {
  WORK_CERTIFICATE = 'WORK_CERTIFICATE',

  SALARY_ATTESTATION = 'SALARY_ATTESTATION',

  CNSS_DECLARATION = 'CNSS_DECLARATION',

  EMPLOYER_DECLARATION = 'EMPLOYER_DECLARATION',

  CAVIS_DECLARATION = 'CAVIS_DECLARATION',

  IRPP_WITHHOLDING = 'IRPP_WITHHOLDING',
}
