package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccountPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPlanAllPropertiesEquals(AccountPlan expected, AccountPlan actual) {
        assertAccountPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPlanAllUpdatablePropertiesEquals(AccountPlan expected, AccountPlan actual) {
        assertAccountPlanUpdatableFieldsEquals(expected, actual);
        assertAccountPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPlanAutoGeneratedPropertiesEquals(AccountPlan expected, AccountPlan actual) {
        assertThat(actual)
            .as("Verify AccountPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPlanUpdatableFieldsEquals(AccountPlan expected, AccountPlan actual) {
        assertThat(actual)
            .as("Verify AccountPlan relevant properties")
            .satisfies(a -> assertThat(a.getAccountCode()).as("check accountCode").isEqualTo(expected.getAccountCode()))
            .satisfies(a -> assertThat(a.getAccountLabel()).as("check accountLabel").isEqualTo(expected.getAccountLabel()))
            .satisfies(a -> assertThat(a.getAccountLabelAr()).as("check accountLabelAr").isEqualTo(expected.getAccountLabelAr()))
            .satisfies(a -> assertThat(a.getAccountType()).as("check accountType").isEqualTo(expected.getAccountType()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPlanUpdatableRelationshipsEquals(AccountPlan expected, AccountPlan actual) {
        assertThat(actual)
            .as("Verify AccountPlan relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
