package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class AccountingEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingEntryAllPropertiesEquals(AccountingEntry expected, AccountingEntry actual) {
        assertAccountingEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountingEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingEntryAllUpdatablePropertiesEquals(AccountingEntry expected, AccountingEntry actual) {
        assertAccountingEntryUpdatableFieldsEquals(expected, actual);
        assertAccountingEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingEntryAutoGeneratedPropertiesEquals(AccountingEntry expected, AccountingEntry actual) {
        assertThat(actual)
            .as("Verify AccountingEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingEntryUpdatableFieldsEquals(AccountingEntry expected, AccountingEntry actual) {
        assertThat(actual)
            .as("Verify AccountingEntry relevant properties")
            .satisfies(a -> assertThat(a.getEntryDate()).as("check entryDate").isEqualTo(expected.getEntryDate()))
            .satisfies(a -> assertThat(a.getJournalRef()).as("check journalRef").isEqualTo(expected.getJournalRef()))
            .satisfies(a -> assertThat(a.getEntryType()).as("check entryType").isEqualTo(expected.getEntryType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDebitAccount()).as("check debitAccount").isEqualTo(expected.getDebitAccount()))
            .satisfies(a -> assertThat(a.getCreditAccount()).as("check creditAccount").isEqualTo(expected.getCreditAccount()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getExportedAt()).as("check exportedAt").isEqualTo(expected.getExportedAt()))
            .satisfies(a -> assertThat(a.getExportFormat()).as("check exportFormat").isEqualTo(expected.getExportFormat()))
            .satisfies(a -> assertThat(a.getExportRef()).as("check exportRef").isEqualTo(expected.getExportRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountingEntryUpdatableRelationshipsEquals(AccountingEntry expected, AccountingEntry actual) {
        assertThat(actual)
            .as("Verify AccountingEntry relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getPayrollPeriod()).as("check payrollPeriod").isEqualTo(expected.getPayrollPeriod()));
    }
}
