package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class AdvanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvanceAllPropertiesEquals(Advance expected, Advance actual) {
        assertAdvanceAutoGeneratedPropertiesEquals(expected, actual);
        assertAdvanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvanceAllUpdatablePropertiesEquals(Advance expected, Advance actual) {
        assertAdvanceUpdatableFieldsEquals(expected, actual);
        assertAdvanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvanceAutoGeneratedPropertiesEquals(Advance expected, Advance actual) {
        assertThat(actual)
            .as("Verify Advance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvanceUpdatableFieldsEquals(Advance expected, Advance actual) {
        assertThat(actual)
            .as("Verify Advance relevant properties")
            .satisfies(a -> assertThat(a.getRequestDate()).as("check requestDate").isEqualTo(expected.getRequestDate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getDeductionMonth()).as("check deductionMonth").isEqualTo(expected.getDeductionMonth()))
            .satisfies(a -> assertThat(a.getDeductionYear()).as("check deductionYear").isEqualTo(expected.getDeductionYear()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getApprovedBy()).as("check approvedBy").isEqualTo(expected.getApprovedBy()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvanceUpdatableRelationshipsEquals(Advance expected, Advance actual) {
        assertThat(actual)
            .as("Verify Advance relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getPaySlip()).as("check paySlip").isEqualTo(expected.getPaySlip()))
            .satisfies(a -> assertThat(a.getApprovedByUser()).as("check approvedByUser").isEqualTo(expected.getApprovedByUser()));
    }
}
