package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class BonusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBonusAllPropertiesEquals(Bonus expected, Bonus actual) {
        assertBonusAutoGeneratedPropertiesEquals(expected, actual);
        assertBonusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBonusAllUpdatablePropertiesEquals(Bonus expected, Bonus actual) {
        assertBonusUpdatableFieldsEquals(expected, actual);
        assertBonusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBonusAutoGeneratedPropertiesEquals(Bonus expected, Bonus actual) {
        assertThat(actual)
            .as("Verify Bonus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBonusUpdatableFieldsEquals(Bonus expected, Bonus actual) {
        assertThat(actual)
            .as("Verify Bonus relevant properties")
            .satisfies(a -> assertThat(a.getBonusType()).as("check bonusType").isEqualTo(expected.getBonusType()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getTaxable()).as("check taxable").isEqualTo(expected.getTaxable()))
            .satisfies(a -> assertThat(a.getMonth()).as("check month").isEqualTo(expected.getMonth()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBonusUpdatableRelationshipsEquals(Bonus expected, Bonus actual) {
        assertThat(actual)
            .as("Verify Bonus relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getPaySlip()).as("check paySlip").isEqualTo(expected.getPaySlip()));
    }
}
