package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionAllPropertiesEquals(ChatSession expected, ChatSession actual) {
        assertChatSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertChatSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionAllUpdatablePropertiesEquals(ChatSession expected, ChatSession actual) {
        assertChatSessionUpdatableFieldsEquals(expected, actual);
        assertChatSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionAutoGeneratedPropertiesEquals(ChatSession expected, ChatSession actual) {
        assertThat(actual)
            .as("Verify ChatSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionUpdatableFieldsEquals(ChatSession expected, ChatSession actual) {
        assertThat(actual)
            .as("Verify ChatSession relevant properties")
            .satisfies(a -> assertThat(a.getChannel()).as("check channel").isEqualTo(expected.getChannel()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getEndedAt()).as("check endedAt").isEqualTo(expected.getEndedAt()))
            .satisfies(a -> assertThat(a.getEscalatedAt()).as("check escalatedAt").isEqualTo(expected.getEscalatedAt()))
            .satisfies(a -> assertThat(a.getEscalatedTo()).as("check escalatedTo").isEqualTo(expected.getEscalatedTo()))
            .satisfies(a -> assertThat(a.getContextData()).as("check contextData").isEqualTo(expected.getContextData()))
            .satisfies(a -> assertThat(a.getSatisfactionScore()).as("check satisfactionScore").isEqualTo(expected.getSatisfactionScore()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatSessionUpdatableRelationshipsEquals(ChatSession expected, ChatSession actual) {
        assertThat(actual)
            .as("Verify ChatSession relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()));
    }
}
