package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class CnssRateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCnssRateAllPropertiesEquals(CnssRate expected, CnssRate actual) {
        assertCnssRateAutoGeneratedPropertiesEquals(expected, actual);
        assertCnssRateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCnssRateAllUpdatablePropertiesEquals(CnssRate expected, CnssRate actual) {
        assertCnssRateUpdatableFieldsEquals(expected, actual);
        assertCnssRateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCnssRateAutoGeneratedPropertiesEquals(CnssRate expected, CnssRate actual) {
        assertThat(actual)
            .as("Verify CnssRate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCnssRateUpdatableFieldsEquals(CnssRate expected, CnssRate actual) {
        assertThat(actual)
            .as("Verify CnssRate relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a ->
                assertThat(a.getSalaryCeiling())
                    .as("check salaryCeiling")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSalaryCeiling())
            )
            .satisfies(a ->
                assertThat(a.getEmployeeRate())
                    .as("check employeeRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getEmployeeRate())
            )
            .satisfies(a ->
                assertThat(a.getEmployerRate())
                    .as("check employerRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getEmployerRate())
            )
            .satisfies(a ->
                assertThat(a.getCavisEmployee())
                    .as("check cavisEmployee")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCavisEmployee())
            )
            .satisfies(a ->
                assertThat(a.getCavisEmployer())
                    .as("check cavisEmployer")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCavisEmployer())
            )
            .satisfies(a -> assertThat(a.getSmig()).as("check smig").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSmig()))
            .satisfies(a -> assertThat(a.getEffectiveFrom()).as("check effectiveFrom").isEqualTo(expected.getEffectiveFrom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCnssRateUpdatableRelationshipsEquals(CnssRate expected, CnssRate actual) {
        assertThat(actual)
            .as("Verify CnssRate relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
