package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class CompanySubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionAllPropertiesEquals(CompanySubscription expected, CompanySubscription actual) {
        assertCompanySubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertCompanySubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionAllUpdatablePropertiesEquals(CompanySubscription expected, CompanySubscription actual) {
        assertCompanySubscriptionUpdatableFieldsEquals(expected, actual);
        assertCompanySubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionAutoGeneratedPropertiesEquals(CompanySubscription expected, CompanySubscription actual) {
        assertThat(actual)
            .as("Verify CompanySubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionUpdatableFieldsEquals(CompanySubscription expected, CompanySubscription actual) {
        assertThat(actual)
            .as("Verify CompanySubscription relevant properties")
            .satisfies(a -> assertThat(a.getPlan()).as("check plan").isEqualTo(expected.getPlan()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getMaxEmployees()).as("check maxEmployees").isEqualTo(expected.getMaxEmployees()))
            .satisfies(a ->
                assertThat(a.getPriceHT()).as("check priceHT").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPriceHT())
            )
            .satisfies(a -> assertThat(a.getBillingDay()).as("check billingDay").isEqualTo(expected.getBillingDay()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getRenewalDate()).as("check renewalDate").isEqualTo(expected.getRenewalDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionUpdatableRelationshipsEquals(CompanySubscription expected, CompanySubscription actual) {
        // empty method
    }
}
