package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class ContractAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractAllPropertiesEquals(Contract expected, Contract actual) {
        assertContractAutoGeneratedPropertiesEquals(expected, actual);
        assertContractAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractAllUpdatablePropertiesEquals(Contract expected, Contract actual) {
        assertContractUpdatableFieldsEquals(expected, actual);
        assertContractUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractAutoGeneratedPropertiesEquals(Contract expected, Contract actual) {
        assertThat(actual)
            .as("Verify Contract auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractUpdatableFieldsEquals(Contract expected, Contract actual) {
        assertThat(actual)
            .as("Verify Contract relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getContractType()).as("check contractType").isEqualTo(expected.getContractType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getSignedDate()).as("check signedDate").isEqualTo(expected.getSignedDate()))
            .satisfies(a ->
                assertThat(a.getBaseSalary())
                    .as("check baseSalary")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBaseSalary())
            )
            .satisfies(a -> assertThat(a.getWorkingHoursWeek()).as("check workingHoursWeek").isEqualTo(expected.getWorkingHoursWeek()))
            .satisfies(a -> assertThat(a.getWorkingDaysWeek()).as("check workingDaysWeek").isEqualTo(expected.getWorkingDaysWeek()))
            .satisfies(a ->
                assertThat(a.getConventionCollective()).as("check conventionCollective").isEqualTo(expected.getConventionCollective())
            )
            .satisfies(a -> assertThat(a.getTrialPeriodMonths()).as("check trialPeriodMonths").isEqualTo(expected.getTrialPeriodMonths()))
            .satisfies(a -> assertThat(a.getRenewalCount()).as("check renewalCount").isEqualTo(expected.getRenewalCount()))
            .satisfies(a -> assertThat(a.getDocumentUrl()).as("check documentUrl").isEqualTo(expected.getDocumentUrl()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractUpdatableRelationshipsEquals(Contract expected, Contract actual) {
        assertThat(actual)
            .as("Verify Contract relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }
}
