package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmployeeHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeHistoryAllPropertiesEquals(EmployeeHistory expected, EmployeeHistory actual) {
        assertEmployeeHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertEmployeeHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeHistoryAllUpdatablePropertiesEquals(EmployeeHistory expected, EmployeeHistory actual) {
        assertEmployeeHistoryUpdatableFieldsEquals(expected, actual);
        assertEmployeeHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeHistoryAutoGeneratedPropertiesEquals(EmployeeHistory expected, EmployeeHistory actual) {
        assertThat(actual)
            .as("Verify EmployeeHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeHistoryUpdatableFieldsEquals(EmployeeHistory expected, EmployeeHistory actual) {
        assertThat(actual)
            .as("Verify EmployeeHistory relevant properties")
            .satisfies(a -> assertThat(a.getFieldName()).as("check fieldName").isEqualTo(expected.getFieldName()))
            .satisfies(a -> assertThat(a.getOldValue()).as("check oldValue").isEqualTo(expected.getOldValue()))
            .satisfies(a -> assertThat(a.getNewValue()).as("check newValue").isEqualTo(expected.getNewValue()))
            .satisfies(a -> assertThat(a.getChangedAt()).as("check changedAt").isEqualTo(expected.getChangedAt()))
            .satisfies(a -> assertThat(a.getChangedBy()).as("check changedBy").isEqualTo(expected.getChangedBy()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeeHistoryUpdatableRelationshipsEquals(EmployeeHistory expected, EmployeeHistory actual) {
        assertThat(actual)
            .as("Verify EmployeeHistory relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()));
    }
}
