package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class JobPositionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobPositionAllPropertiesEquals(JobPosition expected, JobPosition actual) {
        assertJobPositionAutoGeneratedPropertiesEquals(expected, actual);
        assertJobPositionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobPositionAllUpdatablePropertiesEquals(JobPosition expected, JobPosition actual) {
        assertJobPositionUpdatableFieldsEquals(expected, actual);
        assertJobPositionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobPositionAutoGeneratedPropertiesEquals(JobPosition expected, JobPosition actual) {
        assertThat(actual)
            .as("Verify JobPosition auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobPositionUpdatableFieldsEquals(JobPosition expected, JobPosition actual) {
        assertThat(actual)
            .as("Verify JobPosition relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getMinSalary()).as("check minSalary").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMinSalary())
            )
            .satisfies(a ->
                assertThat(a.getMaxSalary()).as("check maxSalary").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMaxSalary())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobPositionUpdatableRelationshipsEquals(JobPosition expected, JobPosition actual) {
        assertThat(actual)
            .as("Verify JobPosition relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()));
    }
}
