package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KnowledgeDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeDocumentAllPropertiesEquals(KnowledgeDocument expected, KnowledgeDocument actual) {
        assertKnowledgeDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertKnowledgeDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeDocumentAllUpdatablePropertiesEquals(KnowledgeDocument expected, KnowledgeDocument actual) {
        assertKnowledgeDocumentUpdatableFieldsEquals(expected, actual);
        assertKnowledgeDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeDocumentAutoGeneratedPropertiesEquals(KnowledgeDocument expected, KnowledgeDocument actual) {
        assertThat(actual)
            .as("Verify KnowledgeDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeDocumentUpdatableFieldsEquals(KnowledgeDocument expected, KnowledgeDocument actual) {
        assertThat(actual)
            .as("Verify KnowledgeDocument relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getFileUrl()).as("check fileUrl").isEqualTo(expected.getFileUrl()))
            .satisfies(a -> assertThat(a.getVectorIndexed()).as("check vectorIndexed").isEqualTo(expected.getVectorIndexed()))
            .satisfies(a -> assertThat(a.getIndexedAt()).as("check indexedAt").isEqualTo(expected.getIndexedAt()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeDocumentUpdatableRelationshipsEquals(KnowledgeDocument expected, KnowledgeDocument actual) {
        assertThat(actual)
            .as("Verify KnowledgeDocument relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
