package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeaveRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveRequestAllPropertiesEquals(LeaveRequest expected, LeaveRequest actual) {
        assertLeaveRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertLeaveRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveRequestAllUpdatablePropertiesEquals(LeaveRequest expected, LeaveRequest actual) {
        assertLeaveRequestUpdatableFieldsEquals(expected, actual);
        assertLeaveRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveRequestAutoGeneratedPropertiesEquals(LeaveRequest expected, LeaveRequest actual) {
        assertThat(actual)
            .as("Verify LeaveRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveRequestUpdatableFieldsEquals(LeaveRequest expected, LeaveRequest actual) {
        assertThat(actual)
            .as("Verify LeaveRequest relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getNumberOfDays()).as("check numberOfDays").isEqualTo(expected.getNumberOfDays()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()))
            .satisfies(a -> assertThat(a.getManagerComment()).as("check managerComment").isEqualTo(expected.getManagerComment()))
            .satisfies(a -> assertThat(a.getEmployeeComment()).as("check employeeComment").isEqualTo(expected.getEmployeeComment()))
            .satisfies(a -> assertThat(a.getDocumentUrl()).as("check documentUrl").isEqualTo(expected.getDocumentUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveRequestUpdatableRelationshipsEquals(LeaveRequest expected, LeaveRequest actual) {
        assertThat(actual)
            .as("Verify LeaveRequest relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getLeaveType()).as("check leaveType").isEqualTo(expected.getLeaveType()))
            .satisfies(a -> assertThat(a.getApprovedBy()).as("check approvedBy").isEqualTo(expected.getApprovedBy()));
    }
}
