package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class LeaveBalanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveBalanceAllPropertiesEquals(LeaveBalance expected, LeaveBalance actual) {
        assertLeaveBalanceAutoGeneratedPropertiesEquals(expected, actual);
        assertLeaveBalanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveBalanceAllUpdatablePropertiesEquals(LeaveBalance expected, LeaveBalance actual) {
        assertLeaveBalanceUpdatableFieldsEquals(expected, actual);
        assertLeaveBalanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveBalanceAutoGeneratedPropertiesEquals(LeaveBalance expected, LeaveBalance actual) {
        assertThat(actual)
            .as("Verify LeaveBalance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveBalanceUpdatableFieldsEquals(LeaveBalance expected, LeaveBalance actual) {
        assertThat(actual)
            .as("Verify LeaveBalance relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a ->
                assertThat(a.getEntitled()).as("check entitled").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getEntitled())
            )
            .satisfies(a -> assertThat(a.getTaken()).as("check taken").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaken()))
            .satisfies(a ->
                assertThat(a.getPending()).as("check pending").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPending())
            )
            .satisfies(a ->
                assertThat(a.getCarryOver()).as("check carryOver").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCarryOver())
            )
            .satisfies(a ->
                assertThat(a.getRemaining()).as("check remaining").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRemaining())
            )
            .satisfies(a -> assertThat(a.getLastUpdatedAt()).as("check lastUpdatedAt").isEqualTo(expected.getLastUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveBalanceUpdatableRelationshipsEquals(LeaveBalance expected, LeaveBalance actual) {
        assertThat(actual)
            .as("Verify LeaveBalance relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getLeaveType()).as("check leaveType").isEqualTo(expected.getLeaveType()));
    }
}
