package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeaveTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveTypeAllPropertiesEquals(LeaveType expected, LeaveType actual) {
        assertLeaveTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertLeaveTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveTypeAllUpdatablePropertiesEquals(LeaveType expected, LeaveType actual) {
        assertLeaveTypeUpdatableFieldsEquals(expected, actual);
        assertLeaveTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveTypeAutoGeneratedPropertiesEquals(LeaveType expected, LeaveType actual) {
        assertThat(actual)
            .as("Verify LeaveType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveTypeUpdatableFieldsEquals(LeaveType expected, LeaveType actual) {
        assertThat(actual)
            .as("Verify LeaveType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getMaxDaysPerYear()).as("check maxDaysPerYear").isEqualTo(expected.getMaxDaysPerYear()))
            .satisfies(a -> assertThat(a.getCarryOverDays()).as("check carryOverDays").isEqualTo(expected.getCarryOverDays()))
            .satisfies(a -> assertThat(a.getPaid()).as("check paid").isEqualTo(expected.getPaid()))
            .satisfies(a -> assertThat(a.getRequiresMedical()).as("check requiresMedical").isEqualTo(expected.getRequiresMedical()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeaveTypeUpdatableRelationshipsEquals(LeaveType expected, LeaveType actual) {
        assertThat(actual)
            .as("Verify LeaveType relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
