package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OfficialDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialDocumentAllPropertiesEquals(OfficialDocument expected, OfficialDocument actual) {
        assertOfficialDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertOfficialDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialDocumentAllUpdatablePropertiesEquals(OfficialDocument expected, OfficialDocument actual) {
        assertOfficialDocumentUpdatableFieldsEquals(expected, actual);
        assertOfficialDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialDocumentAutoGeneratedPropertiesEquals(OfficialDocument expected, OfficialDocument actual) {
        assertThat(actual)
            .as("Verify OfficialDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialDocumentUpdatableFieldsEquals(OfficialDocument expected, OfficialDocument actual) {
        assertThat(actual)
            .as("Verify OfficialDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocType()).as("check docType").isEqualTo(expected.getDocType()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getMonth()).as("check month").isEqualTo(expected.getMonth()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getGeneratedAt()).as("check generatedAt").isEqualTo(expected.getGeneratedAt()))
            .satisfies(a -> assertThat(a.getFileUrl()).as("check fileUrl").isEqualTo(expected.getFileUrl()))
            .satisfies(a -> assertThat(a.getSignedBy()).as("check signedBy").isEqualTo(expected.getSignedBy()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialDocumentUpdatableRelationshipsEquals(OfficialDocument expected, OfficialDocument actual) {
        assertThat(actual)
            .as("Verify OfficialDocument relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getGeneratedBy()).as("check generatedBy").isEqualTo(expected.getGeneratedBy()));
    }
}
