package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PayrollPeriodAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayrollPeriodAllPropertiesEquals(PayrollPeriod expected, PayrollPeriod actual) {
        assertPayrollPeriodAutoGeneratedPropertiesEquals(expected, actual);
        assertPayrollPeriodAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayrollPeriodAllUpdatablePropertiesEquals(PayrollPeriod expected, PayrollPeriod actual) {
        assertPayrollPeriodUpdatableFieldsEquals(expected, actual);
        assertPayrollPeriodUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayrollPeriodAutoGeneratedPropertiesEquals(PayrollPeriod expected, PayrollPeriod actual) {
        assertThat(actual)
            .as("Verify PayrollPeriod auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayrollPeriodUpdatableFieldsEquals(PayrollPeriod expected, PayrollPeriod actual) {
        assertThat(actual)
            .as("Verify PayrollPeriod relevant properties")
            .satisfies(a -> assertThat(a.getMonth()).as("check month").isEqualTo(expected.getMonth()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCalculatedAt()).as("check calculatedAt").isEqualTo(expected.getCalculatedAt()))
            .satisfies(a -> assertThat(a.getValidatedAt()).as("check validatedAt").isEqualTo(expected.getValidatedAt()))
            .satisfies(a -> assertThat(a.getLockedAt()).as("check lockedAt").isEqualTo(expected.getLockedAt()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayrollPeriodUpdatableRelationshipsEquals(PayrollPeriod expected, PayrollPeriod actual) {
        assertThat(actual)
            .as("Verify PayrollPeriod relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }
}
