package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PayrollPeriodAsserts {

    public static void assertPayrollPeriodAutoGeneratedPropertiesEquals(
        PayrollPeriod expected,
        PayrollPeriod actual
    ) {
        assertThat(expected)
            .as("Verify PayrollPeriod auto-generated properties")
            .satisfies(p -> assertThat(p.getId()).as("check id").isEqualTo(actual.getId()));
    }

    public static void assertPayrollPeriodAllPropertiesEquals(
        PayrollPeriod expected,
        PayrollPeriod actual
    ) {
        assertPayrollPeriodAutoGeneratedPropertiesEquals(expected, actual);
        assertPayrollPeriodAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertPayrollPeriodUpdatableFieldsEquals(
        PayrollPeriod expected,
        PayrollPeriod actual
    ) {
        assertPayrollPeriodAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertPayrollPeriodAllUpdatablePropertiesEquals(
        PayrollPeriod expected,
        PayrollPeriod actual
    ) {
        assertThat(expected)
            .as("Verify PayrollPeriod relevant properties")
            .satisfies(p -> {
                assertThat(p.getMonth()).as("check month").isEqualTo(actual.getMonth());
                assertThat(p.getYear()).as("check year").isEqualTo(actual.getYear());
                assertThat(p.getStatus()).as("check status").isEqualTo(actual.getStatus());
            });
    }
}
