package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class PaySlipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipAllPropertiesEquals(PaySlip expected, PaySlip actual) {
        assertPaySlipAutoGeneratedPropertiesEquals(expected, actual);
        assertPaySlipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipAllUpdatablePropertiesEquals(PaySlip expected, PaySlip actual) {
        assertPaySlipUpdatableFieldsEquals(expected, actual);
        assertPaySlipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipAutoGeneratedPropertiesEquals(PaySlip expected, PaySlip actual) {
        assertThat(actual)
            .as("Verify PaySlip auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipUpdatableFieldsEquals(PaySlip expected, PaySlip actual) {
        assertThat(actual)
            .as("Verify PaySlip relevant properties")
            .satisfies(a -> assertThat(a.getMonth()).as("check month").isEqualTo(expected.getMonth()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a ->
                assertThat(a.getBaseSalary())
                    .as("check baseSalary")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBaseSalary())
            )
            .satisfies(a ->
                assertThat(a.getTotalGains())
                    .as("check totalGains")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalGains())
            )
            .satisfies(a ->
                assertThat(a.getTotalDeductions())
                    .as("check totalDeductions")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalDeductions())
            )
            .satisfies(a ->
                assertThat(a.getGrossSalary())
                    .as("check grossSalary")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getGrossSalary())
            )
            .satisfies(a ->
                assertThat(a.getCnssSalaryAmount())
                    .as("check cnssSalaryAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCnssSalaryAmount())
            )
            .satisfies(a ->
                assertThat(a.getCavisAmount())
                    .as("check cavisAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCavisAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxableIncome())
                    .as("check taxableIncome")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTaxableIncome())
            )
            .satisfies(a ->
                assertThat(a.getIrppAmount())
                    .as("check irppAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getIrppAmount())
            )
            .satisfies(a ->
                assertThat(a.getNetSalary()).as("check netSalary").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getNetSalary())
            )
            .satisfies(a ->
                assertThat(a.getEmployerCnss())
                    .as("check employerCnss")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getEmployerCnss())
            )
            .satisfies(a ->
                assertThat(a.getEmployerCavis())
                    .as("check employerCavis")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getEmployerCavis())
            )
            .satisfies(a ->
                assertThat(a.getTotalEmployerCost())
                    .as("check totalEmployerCost")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalEmployerCost())
            )
            .satisfies(a -> assertThat(a.getWorkedDays()).as("check workedDays").isEqualTo(expected.getWorkedDays()))
            .satisfies(a -> assertThat(a.getPaidLeaveDays()).as("check paidLeaveDays").isEqualTo(expected.getPaidLeaveDays()))
            .satisfies(a -> assertThat(a.getUnpaidDays()).as("check unpaidDays").isEqualTo(expected.getUnpaidDays()))
            .satisfies(a ->
                assertThat(a.getOvertimeHours())
                    .as("check overtimeHours")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOvertimeHours())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPdfUrl()).as("check pdfUrl").isEqualTo(expected.getPdfUrl()))
            .satisfies(a -> assertThat(a.getGeneratedAt()).as("check generatedAt").isEqualTo(expected.getGeneratedAt()))
            .satisfies(a -> assertThat(a.getSentToEmployeeAt()).as("check sentToEmployeeAt").isEqualTo(expected.getSentToEmployeeAt()))
            .satisfies(a -> assertThat(a.getBankTransferRef()).as("check bankTransferRef").isEqualTo(expected.getBankTransferRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipUpdatableRelationshipsEquals(PaySlip expected, PaySlip actual) {
        assertThat(actual)
            .as("Verify PaySlip relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getPayrollPeriod()).as("check payrollPeriod").isEqualTo(expected.getPayrollPeriod()))
            .satisfies(a -> assertThat(a.getContract()).as("check contract").isEqualTo(expected.getContract()));
    }
}
