package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class PaySlipLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipLineAllPropertiesEquals(PaySlipLine expected, PaySlipLine actual) {
        assertPaySlipLineAutoGeneratedPropertiesEquals(expected, actual);
        assertPaySlipLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipLineAllUpdatablePropertiesEquals(PaySlipLine expected, PaySlipLine actual) {
        assertPaySlipLineUpdatableFieldsEquals(expected, actual);
        assertPaySlipLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipLineAutoGeneratedPropertiesEquals(PaySlipLine expected, PaySlipLine actual) {
        assertThat(actual)
            .as("Verify PaySlipLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipLineUpdatableFieldsEquals(PaySlipLine expected, PaySlipLine actual) {
        assertThat(actual)
            .as("Verify PaySlipLine relevant properties")
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getRubriqueCode()).as("check rubriqueCode").isEqualTo(expected.getRubriqueCode()))
            .satisfies(a -> assertThat(a.getRubriqueLabel()).as("check rubriqueLabel").isEqualTo(expected.getRubriqueLabel()))
            .satisfies(a -> assertThat(a.getRubriqueType()).as("check rubriqueType").isEqualTo(expected.getRubriqueType()))
            .satisfies(a -> assertThat(a.getBase()).as("check base").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBase()))
            .satisfies(a -> assertThat(a.getRate()).as("check rate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getTaxable()).as("check taxable").isEqualTo(expected.getTaxable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaySlipLineUpdatableRelationshipsEquals(PaySlipLine expected, PaySlipLine actual) {
        assertThat(actual)
            .as("Verify PaySlipLine relationships")
            .satisfies(a -> assertThat(a.getPaySlip()).as("check paySlip").isEqualTo(expected.getPaySlip()))
            .satisfies(a -> assertThat(a.getRubrique()).as("check rubrique").isEqualTo(expected.getRubrique()));
    }
}
