package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublicHolidayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicHolidayAllPropertiesEquals(PublicHoliday expected, PublicHoliday actual) {
        assertPublicHolidayAutoGeneratedPropertiesEquals(expected, actual);
        assertPublicHolidayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicHolidayAllUpdatablePropertiesEquals(PublicHoliday expected, PublicHoliday actual) {
        assertPublicHolidayUpdatableFieldsEquals(expected, actual);
        assertPublicHolidayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicHolidayAutoGeneratedPropertiesEquals(PublicHoliday expected, PublicHoliday actual) {
        assertThat(actual)
            .as("Verify PublicHoliday auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicHolidayUpdatableFieldsEquals(PublicHoliday expected, PublicHoliday actual) {
        assertThat(actual)
            .as("Verify PublicHoliday relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNameAr()).as("check nameAr").isEqualTo(expected.getNameAr()))
            .satisfies(a -> assertThat(a.getHolidayDate()).as("check holidayDate").isEqualTo(expected.getHolidayDate()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getIsRecurring()).as("check isRecurring").isEqualTo(expected.getIsRecurring()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicHolidayUpdatableRelationshipsEquals(PublicHoliday expected, PublicHoliday actual) {
        // empty method
    }
}
