package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class RegulatoryParamAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegulatoryParamAllPropertiesEquals(RegulatoryParam expected, RegulatoryParam actual) {
        assertRegulatoryParamAutoGeneratedPropertiesEquals(expected, actual);
        assertRegulatoryParamAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegulatoryParamAllUpdatablePropertiesEquals(RegulatoryParam expected, RegulatoryParam actual) {
        assertRegulatoryParamUpdatableFieldsEquals(expected, actual);
        assertRegulatoryParamUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegulatoryParamAutoGeneratedPropertiesEquals(RegulatoryParam expected, RegulatoryParam actual) {
        assertThat(actual)
            .as("Verify RegulatoryParam auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegulatoryParamUpdatableFieldsEquals(RegulatoryParam expected, RegulatoryParam actual) {
        assertThat(actual)
            .as("Verify RegulatoryParam relevant properties")
            .satisfies(a -> assertThat(a.getParamKey()).as("check paramKey").isEqualTo(expected.getParamKey()))
            .satisfies(a -> assertThat(a.getParamLabel()).as("check paramLabel").isEqualTo(expected.getParamLabel()))
            .satisfies(a ->
                assertThat(a.getNumericValue())
                    .as("check numericValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getNumericValue())
            )
            .satisfies(a -> assertThat(a.getTextValue()).as("check textValue").isEqualTo(expected.getTextValue()))
            .satisfies(a -> assertThat(a.getEffectiveFrom()).as("check effectiveFrom").isEqualTo(expected.getEffectiveFrom()))
            .satisfies(a -> assertThat(a.getEffectiveTo()).as("check effectiveTo").isEqualTo(expected.getEffectiveTo()))
            .satisfies(a -> assertThat(a.getLegalReference()).as("check legalReference").isEqualTo(expected.getLegalReference()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegulatoryParamUpdatableRelationshipsEquals(RegulatoryParam expected, RegulatoryParam actual) {
        // empty method
    }
}
