package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class RubriqueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubriqueAllPropertiesEquals(Rubrique expected, Rubrique actual) {
        assertRubriqueAutoGeneratedPropertiesEquals(expected, actual);
        assertRubriqueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubriqueAllUpdatablePropertiesEquals(Rubrique expected, Rubrique actual) {
        assertRubriqueUpdatableFieldsEquals(expected, actual);
        assertRubriqueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubriqueAutoGeneratedPropertiesEquals(Rubrique expected, Rubrique actual) {
        assertThat(actual)
            .as("Verify Rubrique auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubriqueUpdatableFieldsEquals(Rubrique expected, Rubrique actual) {
        assertThat(actual)
            .as("Verify Rubrique relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getLabelAr()).as("check labelAr").isEqualTo(expected.getLabelAr()))
            .satisfies(a -> assertThat(a.getRubriqueType()).as("check rubriqueType").isEqualTo(expected.getRubriqueType()))
            .satisfies(a -> assertThat(a.getBase()).as("check base").isEqualTo(expected.getBase()))
            .satisfies(a -> assertThat(a.getRate()).as("check rate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRate()))
            .satisfies(a ->
                assertThat(a.getFixedAmount())
                    .as("check fixedAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFixedAmount())
            )
            .satisfies(a -> assertThat(a.getFormula()).as("check formula").isEqualTo(expected.getFormula()))
            .satisfies(a -> assertThat(a.getTaxable()).as("check taxable").isEqualTo(expected.getTaxable()))
            .satisfies(a -> assertThat(a.getCnssSalary()).as("check cnssSalary").isEqualTo(expected.getCnssSalary()))
            .satisfies(a -> assertThat(a.getCnssEmployer()).as("check cnssEmployer").isEqualTo(expected.getCnssEmployer()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubriqueUpdatableRelationshipsEquals(Rubrique expected, Rubrique actual) {
        assertThat(actual)
            .as("Verify Rubrique relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
