package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class TaxBracketAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxBracketAllPropertiesEquals(TaxBracket expected, TaxBracket actual) {
        assertTaxBracketAutoGeneratedPropertiesEquals(expected, actual);
        assertTaxBracketAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxBracketAllUpdatablePropertiesEquals(TaxBracket expected, TaxBracket actual) {
        assertTaxBracketUpdatableFieldsEquals(expected, actual);
        assertTaxBracketUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxBracketAutoGeneratedPropertiesEquals(TaxBracket expected, TaxBracket actual) {
        assertThat(actual)
            .as("Verify TaxBracket auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxBracketUpdatableFieldsEquals(TaxBracket expected, TaxBracket actual) {
        assertThat(actual)
            .as("Verify TaxBracket relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a ->
                assertThat(a.getMinIncome()).as("check minIncome").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMinIncome())
            )
            .satisfies(a ->
                assertThat(a.getMaxIncome()).as("check maxIncome").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMaxIncome())
            )
            .satisfies(a -> assertThat(a.getRate()).as("check rate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRate()))
            .satisfies(a ->
                assertThat(a.getFixedDeduction())
                    .as("check fixedDeduction")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFixedDeduction())
            )
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxBracketUpdatableRelationshipsEquals(TaxBracket expected, TaxBracket actual) {
        assertThat(actual)
            .as("Verify TaxBracket relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
