package tn.paiezone.rh.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tn.paiezone.rh.domain.AssertUtils.bigDecimalCompareTo;

public class TimeEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryAllPropertiesEquals(TimeEntry expected, TimeEntry actual) {
        assertTimeEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertTimeEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryAllUpdatablePropertiesEquals(TimeEntry expected, TimeEntry actual) {
        assertTimeEntryUpdatableFieldsEquals(expected, actual);
        assertTimeEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryAutoGeneratedPropertiesEquals(TimeEntry expected, TimeEntry actual) {
        assertThat(actual)
            .as("Verify TimeEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryUpdatableFieldsEquals(TimeEntry expected, TimeEntry actual) {
        assertThat(actual)
            .as("Verify TimeEntry relevant properties")
            .satisfies(a -> assertThat(a.getEntryDate()).as("check entryDate").isEqualTo(expected.getEntryDate()))
            .satisfies(a -> assertThat(a.getCheckIn()).as("check checkIn").isEqualTo(expected.getCheckIn()))
            .satisfies(a -> assertThat(a.getCheckOut()).as("check checkOut").isEqualTo(expected.getCheckOut()))
            .satisfies(a ->
                assertThat(a.getWorkedHours())
                    .as("check workedHours")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getWorkedHours())
            )
            .satisfies(a ->
                assertThat(a.getOvertimeHours())
                    .as("check overtimeHours")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOvertimeHours())
            )
            .satisfies(a -> assertThat(a.getLateMinutes()).as("check lateMinutes").isEqualTo(expected.getLateMinutes()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAnomalyNote()).as("check anomalyNote").isEqualTo(expected.getAnomalyNote()))
            .satisfies(a -> assertThat(a.getValidatedBy()).as("check validatedBy").isEqualTo(expected.getValidatedBy()))
            .satisfies(a -> assertThat(a.getValidatedAt()).as("check validatedAt").isEqualTo(expected.getValidatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryUpdatableRelationshipsEquals(TimeEntry expected, TimeEntry actual) {
        assertThat(actual)
            .as("Verify TimeEntry relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getValidatedBy()).as("check validatedByUser").isEqualTo(expected.getValidatedBy()));
    }
}
